# =================== Preserve Generic Signatures (GSON Reflection) ===================

# Keep generic signatures for reflection (used by GSON for lists like List<User>)
-keepattributes Signature

# Keep inner classes, often used for listeners and callbacks in Java
-keepattributes InnerClasses

# Preserve line numbers in stack traces to make debugging easier
-keepattributes SourceFile,LineNumberTable

# =================== Networking Rules (Retrofit, OkHttp, GSON) ===================

-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-keepnames class com.google.gson.annotations.SerializedName

# This keeps all classes in your app's main package
-keep class com.blank_learn.** { *; }

# =================== Firebase & Google Play Services ===================

# Prevent ProGuard from removing or renaming essential SDK classes
-keepnames class com.google.android.gms.common.**
-keepnames class com.google.firebase.**
-keep class com.google.android.gms.internal.firebase-auth.** { *; }
-keep class com.google.firebase.auth.api.internal.* { *; }

# =================== For Parcelable Classes ===================

-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

# =================== Rules generated by R8 for missing classes ===================

-dontwarn proguard.annotation.Keep
-dontwarn proguard.annotation.KeepClassMembers
-keep class im.zego.zegoexpress.** { *; }

# =================== Kotlin Parcelize ===================

# Suppress warning related to kotlinx.parcelize.Parcelize
-dontwarn kotlinx.parcelize.Parcelize
